blank_issues_enabled: false
contact_links:
  - name: OpenZeppelin Compact Tools Community Support
    url: https://github.com/OpenZeppelin/compact-tools/discussions
    about: Please ask and answer questions here.
